version: "3.4"
services:
  updatejson:
    image: ghcr.io/minecrafthopper/dswrap
    restart: always
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dswrap.rule=Host(`${HOST}`)"
        - "traefik.http.routers.dswrap.entrypoints=websecure"
        - "traefik.http.routers.dswrap.tls.certresolver=myresolver"
        - "traefik.http.services.dswrap.loadbalancer.server.port=8080"
